server.servlet.context-path: /api/v1

spring:
  application.name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/ejournal
    username: ejournalapp
    password: ejournalapp
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
      format_sql: true
  liquibase:
    change-log: classpath:/db/changelog.xml
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ejournal

logging.level:
  ru.salix.ejournal: debug
  org.hibernate.SQL: debug
  liquibase: debug