spring:
  application.name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/ejournal
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false