GRANT USAGE ON SCHEMA ejournal TO ejournalapp;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ejournal TO ejournalapp;

GRANT USAGE, SELECT ON ALL sequences IN SCHEMA ejournal TO ejournalapp;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ejournal TO ejournalapp;

ALTER DEFAULT PRIVILEGES IN SCHEMA ejournal GRANT SELECT, USAGE ON sequences TO ejournalapp;

ALTER DEFAULT PRIVILEGES FOR ROLE ejournalapp IN SCHEMA ejournal GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ejournalapp;

ALTER DEFAULT PRIVILEGES FOR ROLE ejournalapp IN SCHEMA ejournal GRANT EXECUTE ON FUNCTIONS TO ejournalapp;